#DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mogu-mysql.cahtqxbh2c1y.ap-northeast-2.rds.amazonaws.com:3306/mogu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mogu
    password: ENC(zwqa2XpuTC4F0IXSX+yWvskk5yj5fxZ7)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#이메일 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: junesuck99
    password: ENC(bbugOkRLdSQYee7msGwYwVNdBhDMyTNhM5IAhbznlss=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #JPA
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  
  #yml추가
  config:
    import: jasypt.yml

#LOG
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace