#DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.130.79.104:3306/mogu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mogu
    password: ENC(wSQhN8p5Eqd/bqi0w2ewmFZZDf5hvBTj)

#JPA
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

#AWS
cloud:
  aws:
    credentials:
      access-key: ENC(UqR1eGsoVsbylYWooGtYNhoffn86UB+gIxVFFQyTvRM=)
      secret-key: ENC(V+wMLAraR2Y1mNTiARqxlqoEykxZLXWvsO/abSeE+N8r4YIsEHD23U37K3CZmLL173vY9tASkEc=)
    s3:
      bucket: frost0807
    stack:
      auto: false
    region:
      static: ap-northeast-2

#yml추가
  config:
    import: jasypt.yml

#LOG
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
